apiVersion: v1
kind: ServiceAccount
metadata:
  name: nekko-lb-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nekko-lb-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nekko-lb-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: nekko-lb-sa
    namespace: default
roleRef:
  kind: Role
  name: nekko-lb-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nekko-lb
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nekko-lb
  template:
    metadata:
      labels:
        app: nekko-lb
    spec:
      serviceAccountName: nekko-lb-sa
      containers:
      - name: nekko-lb
        image: ghcr.io/vidas/nekko-lb:latest
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: nekko-lb-svc
  labels:
    app: nekko-lb
spec:
  ports:
    - protocol: TCP
      port: 3090
      targetPort: 8080
  selector:
    app: nekko-lb
  type: LoadBalancer
