apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nekko-sm
  namespace: default
spec:
  selector:
    matchLabels:
      name: nekko-sm
  template:
    metadata:
      labels:
        name: nekko-sm
        app: nekko-sm
    spec:
      containers:
      - name: nekko-sm
        image: ghcr.io/vidas/nekko-sm:latest
        ports:
          - containerPort: 8050
        args: ["--address=0.0.0.0:8050", "-v=2"]
        volumeMounts:
        - name: model-cache-dir
          mountPath: /var/lib/nekko/cache
      volumes:
      - name: model-cache-dir
        hostPath:
          path: /var/nekko/cache
      # Allow scheduling on control plane nodes
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule


